# Generated by Django 5.0.6 on 2024-06-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroAdopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatos',
            old_name='Edad',
            new_name='Edad_Meses',
        ),
        migrations.RenameField(
            model_name='perros',
            old_name='Edad',
            new_name='Edad_Meses',
        ),
    ]
