# Generated by Django 5.0.6 on 2024-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroAdopcion', '0002_rename_edad_gatos_edad_meses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopted_Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_Lastname', models.CharField(max_length=40)),
                ('User_Adress', models.CharField(max_length=100)),
                ('Celphone_Number', models.IntegerField()),
                ('Pet_Name', models.CharField(max_length=40)),
                ('Pet_Race', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Race', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=40)),
                ('Age', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Race', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=40)),
                ('Age', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Gatos',
        ),
        migrations.DeleteModel(
            name='Mascota_Adoptada',
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
    ]
